# Config file for AI-MaSi excavator


CHANNEL_CONFIGS:

  pump: # name of the channel. Name "pump" is reserved for the pump control channel, and it has special behavior.
    input_channel: None           # The index of the input data array. In Python, indexing is zero-based, meaning the first value is at index 0. Channel "pump" does not use direct control.
    output_channel: 9             # The PWM hat output channel, same as printed on the PCB. Also Zero-based!
    type: pump                    # type of the controlled thing. this is very WIP, just use "angle" for now
    offset: 0                     # pump does not use this but im lazy, the validator checks this so just leave this to 0 for now
    direction: 1                  # change direction. 1 or -1
    idle: -0.15                 # this value gives nice idle speed when used to control the pump. ESC dependant. 0 would be ok
    multiplier: 0.05             # how much pump speeds up when "affects_pump" channels are active


  trackR: # names trackR and trackL also have special behavior! They are used to control the tracks of the excavator.
    input_channel: 4
    output_channel: 5
    type: angle                   # even though tracks don't use angles, it's best to keep this as "angle" for now. Prob better to depreciate and just set output specific PWM range.
    affects_pump: false           # Set to True if you want this channel to inrease pump speed when the servo is moved.
    offset: 0                     # Servo start point offset. 0 is the middle of the servo range (90).
    direction: 1
    multiplier_positive: 30       # Servo movement scaling factors. About the same as degrees. pos+neg is the full range of the servo.
    multiplier_negative: 30
    gamma_positive: 1.0           # Gamma correction factors for input values.
    gamma_negative: 1.0           # = 1.0: Linear response (no correction).
                                  # < 1.0: Makes the servo more responsive at the beginning of joystick movement
                                  # > 1.0: Makes the servo more responsive at the end of joystick movement.
  trackL:
    input_channel: 5
    output_channel: 1
    type: angle
    affects_pump: false
    offset: 0
    direction: 1
    multiplier_positive: 30
    multiplier_negative: 30
    gamma_positive: 1.0
    gamma_negative: 1.0


  scoop: # otherwise you are free to name the channels as you like.
    input_channel: 0
    output_channel: 2
    type: angle
    affects_pump: true
    offset: 2
    direction: -1
    multiplier_positive: 30
    multiplier_negative: 30
    gamma_positive: 1.0
    gamma_negative: 1.0

  lift_boom:
    input_channel: 1
    output_channel: 3
    type: angle
    affects_pump: true
    offset: -5 # added
    direction: -1
    multiplier_positive: 30
    multiplier_negative: 30
    gamma_positive: 1.0
    gamma_negative: 1.0


  tilt_boom:
    input_channel: 3
    output_channel: 4
    type: angle
    affects_pump: true
    offset: 10
    direction: 1
    multiplier_positive: 30
    multiplier_negative: 30
    gamma_positive: 1.0
    gamma_negative: 1.0

  rotate:
    input_channel: 2
    output_channel: 0
    type: angle
    affects_pump: false
    offset: 0
    direction: -1
    multiplier_positive: 11
    multiplier_negative: 11
    gamma_positive: 1.0
    gamma_negative: 1.0
